import type { ReportName } from '../../api/reports'

export type ReportFormat='text'|'store'|'money'|'quantity'|'identity'|'receipt'|'sale'|'closing'|'count'|'product'|'movement'
export interface ReportColumn{key:string;label:string;format?:ReportFormat;unitKey?:string}
export interface ReportDefinition{label:string;dated:boolean;columns:ReportColumn[]}

export const reportDefinitions:Record<ReportName,ReportDefinition>={
  inventory:{label:'Inventory',dated:false,columns:[{key:'store_id',label:'Store',format:'store'},{key:'sku',label:'SKU'},{key:'location',label:'Location'},{key:'disposition',label:'Disposition'},{key:'quantity',label:'Quantity',format:'quantity',unitKey:'stock_unit'}]},
  movements:{label:'Movements',dated:true,columns:[{key:'business_date',label:'Business date'},{key:'kind',label:'Kind'},{key:'product_id',label:'Product',format:'product'},{key:'quantity',label:'Quantity',format:'quantity',unitKey:'native_unit'},{key:'location_id',label:'Location',format:'movement'},{key:'disposition',label:'Disposition'},{key:'from_location_id',label:'From location',format:'movement'},{key:'to_location_id',label:'To location',format:'movement'},{key:'from_disposition',label:'From disposition'},{key:'to_disposition',label:'To disposition'}]},
  'goods-exceptions':{label:'Goods exceptions',dated:true,columns:[{key:'id',label:'Receipt',format:'receipt'},{key:'store_id',label:'Store',format:'store'},{key:'business_date',label:'Business date'},{key:'status',label:'Status'},{key:'shipment_reference',label:'Shipment reference'}]},
  sales:{label:'Sales',dated:true,columns:[{key:'store_id',label:'Store',format:'store'},{key:'series',label:'Series'},{key:'design',label:'Design'},{key:'unverified_product',label:'Unverified product'},{key:'quantity',label:'Quantity',format:'quantity',unitKey:'native_unit'},{key:'identity_complete',label:'Identity',format:'identity'}]},
  tenders:{label:'Tenders',dated:true,columns:[{key:'tender',label:'Tender'},{key:'recorded_cents',label:'Recorded',format:'money'},{key:'verified_cents',label:'Verified',format:'money'},{key:'refund_cents',label:'Refunds',format:'money'},{key:'unknown_count',label:'Unknown'},{key:'pending_count',label:'Pending'}]},
  'evidence-exceptions':{label:'Evidence exceptions',dated:true,columns:[{key:'evidence_id',label:'Evidence',format:'sale'},{key:'payment_id',label:'Payment'},{key:'store_id',label:'Store',format:'store'},{key:'status',label:'Status'},{key:'created_at',label:'Created'}]},
  'cash-variance':{label:'Cash variance',dated:true,columns:[{key:'store_id',label:'Store',format:'store'},{key:'business_date',label:'Business date'},{key:'status',label:'Status'},{key:'expected_cents',label:'Expected',format:'money'},{key:'counted_cents',label:'Counted',format:'money'},{key:'variance_cents',label:'Variance',format:'money'},{key:'closing_id',label:'Closing',format:'closing'}]},
  'count-discrepancies':{label:'Count discrepancies',dated:true,columns:[{key:'store_id',label:'Store',format:'store'},{key:'business_date',label:'Business date'},{key:'product_id',label:'Product',format:'product'},{key:'expected_quantity',label:'Expected',format:'quantity',unitKey:'native_unit'},{key:'observed_quantity',label:'Observed',format:'quantity',unitKey:'native_unit'},{key:'discrepancy',label:'Discrepancy',format:'quantity',unitKey:'native_unit'},{key:'count_id',label:'Count',format:'count'}]},
  'closed-days':{label:'Closed days',dated:true,columns:[{key:'store_id',label:'Store',format:'store'},{key:'business_date',label:'Business date'},{key:'created_at',label:'Closed at'},{key:'later_adjustment_count',label:'Later adjustments'},{key:'closing_id',label:'Closing',format:'closing'}]},
}
