import { useEffect,useState } from 'react'
import { Alert,Button,Card,Select,Space,Table,Typography } from 'antd'
import { Link,useSearchParams } from 'react-router-dom'
import { downloadReport,getReport,type ReportName,type ReportResult } from '../../api/reports'
import { useAppStore } from '../../store'
const choices:[ReportName,string][]=[['inventory','Inventory'],['movements','Movements'],['goods-exceptions','Goods exceptions'],['sales','Sales'],['tenders','Tenders'],['evidence-exceptions','Evidence exceptions'],['cash-variance','Cash variance'],['count-discrepancies','Count discrepancies'],['closed-days','Closed days']]
export default function ReportsPage(){const store=useAppStore(s=>s.selectedStore);const[params,setParams]=useSearchParams();const name=(params.get('report')||'inventory') as ReportName;const[data,setData]=useState<ReportResult>();const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[exporting,setExporting]=useState(false)
useEffect(()=>{if(!store?.code)return;let current=true;setLoading(true);setError('');getReport(name,{store_code:store.code,from:params.get('from')||'',to:params.get('to')||''}).then(v=>{if(current)setData(v)}).catch((e:any)=>{if(current)setError(e?._serverMessage||'Unable to load report.')}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[name,params,store?.code])
const rows=data?.items||[];const cols=Array.from(new Set(rows.flatMap(r=>Object.keys(r)))).filter(k=>!k.includes('snapshot_json')).map(k=>({title:k.replaceAll('_',' '),dataIndex:k,key:k,render:(v:unknown,row:any)=>k.endsWith('_id')&&row.sale_id?<Link to={`/sales/documents/${row.sale_id}`}>{String(v??'')}</Link>:v==null?'Unknown':String(v)}))
async function exportCsv(){setExporting(true);setError('');try{await downloadReport(name,{store_code:store?.code||'ALL'})}catch{setError('Unable to export this report.')}finally{setExporting(false)}}
return <Space direction="vertical" style={{width:'100%'}} size={16}><div><Typography.Title level={2} style={{marginBottom:0}}>Operational reports</Typography.Title><Typography.Text type="secondary">Authoritative documents, explicit unknowns, no cost or profit estimates.</Typography.Text></div><Card><Space wrap><Select aria-label="Report" value={name} options={choices.map(([value,label])=>({value,label}))} onChange={v=>setParams({report:v})} style={{minWidth:220}}/><Button loading={exporting} onClick={exportCsv}>Export CSV</Button></Space></Card>{error&&<Alert type="error" showIcon message={error}/>} {data&&data.incomplete_count?<Alert type="warning" showIcon message={`${data.incomplete_count} records have unknown monetary totals`}/>:null}<Card><Table loading={loading} rowKey={(r:any)=>JSON.stringify(r)} dataSource={rows} columns={cols} scroll={{x:true}} pagination={{pageSize:50}}/><Typography.Text type="secondary">{data?.total_rows||0} rows</Typography.Text></Card></Space>}
