plugins { id 'com.android.application' }

android {
    namespace 'ca.popcore.cloversync'
    compileSdk 37
    lint { disable 'ExpiredTargetSdkVersion' }
    defaultConfig {
        applicationId 'ca.popcore.cloversync'
        minSdk 26
        targetSdk 29
        versionCode 1
        versionName '0.1-sandbox'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies { implementation 'com.clover.sdk:clover-android-sdk:334' }
